--------------------------------------------------------
--  File created - Wednesday-November-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_AUDITORIA
--------------------------------------------------------

   CREATE SEQUENCE  "ETECHSHOPCONN"."SEQ_AUDITORIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AUDITORIA
--------------------------------------------------------

  CREATE TABLE "ETECHSHOPCONN"."AUDITORIA" 
   (	"ID_AUD" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TABLA" VARCHAR2(50 BYTE), 
	"OPERACION" VARCHAR2(10 BYTE), 
	"ID_REGISTRO" VARCHAR2(50 BYTE), 
	"USUARIO_BD" VARCHAR2(50 BYTE), 
	"FCH_EVENTO" DATE DEFAULT SYSDATE, 
	"DETALLE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARRITO
--------------------------------------------------------

  CREATE TABLE "ETECHSHOPCONN"."CARRITO" 
   (	"ID_USUARIO" NUMBER, 
	"CODIGO_PROD" NUMBER, 
	"CANTIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPRAS
--------------------------------------------------------

  CREATE TABLE "ETECHSHOPCONN"."COMPRAS" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_USUARIO" NUMBER, 
	"TOTAL" NUMBER(10,2), 
	"FECHA" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPRAS_DETALLE
--------------------------------------------------------

  CREATE TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" 
   (	"ID_DETALLE" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_COMPRA" NUMBER, 
	"CODIGO_PROD" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO_UNIT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "ETECHSHOPCONN"."PRODUCTOS" 
   (	"CODIGO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"DETALLE" VARCHAR2(1024 BYTE), 
	"IMAGEN" VARCHAR2(455 BYTE), 
	"PRECIO" NUMBER(10,2), 
	"STOCK" NUMBER DEFAULT 0, 
	"FCH_CREA" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "ETECHSHOPCONN"."USUARIOS" 
   (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CORREO" VARCHAR2(255 BYTE), 
	"CONTRASENA" VARCHAR2(255 BYTE), 
	"INTENTOS" NUMBER DEFAULT 0, 
	"BLOQUEADO" CHAR(1 BYTE) DEFAULT 'N', 
	"FCH_CREA" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CARRITO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETECHSHOPCONN"."PK_CARRITO" ON "ETECHSHOPCONN"."CARRITO" ("ID_USUARIO", "CODIGO_PROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_AUD_PRODUCTOS_U
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ETECHSHOPCONN"."TRG_AUD_PRODUCTOS_U" 
AFTER UPDATE OF precio, stock ON productos
FOR EACH ROW
DECLARE
  v_detalle VARCHAR2(400);
BEGIN
  IF NVL(:OLD.precio, -1) <> NVL(:NEW.precio, -1) THEN
    v_detalle := NVL(v_detalle,'') || 'precio: '||:OLD.precio||' -> '||:NEW.precio||' ';
  END IF;

  IF NVL(:OLD.stock, -1) <> NVL(:NEW.stock, -1) THEN
    v_detalle := NVL(v_detalle,'') || 'stock: '||:OLD.stock||' -> '||:NEW.stock||' ';
  END IF;

  IF v_detalle IS NOT NULL THEN
    INSERT INTO auditoria(tabla, operacion, id_registro, usuario_bd, detalle)
    VALUES ('PRODUCTOS',
            'UPDATE',
            TO_CHAR(:NEW.codigo),
            SYS_CONTEXT('USERENV','SESSION_USER'),
            TRIM(v_detalle));
  END IF;
END;
/
ALTER TRIGGER "ETECHSHOPCONN"."TRG_AUD_PRODUCTOS_U" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STOCK_DISMINUIR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ETECHSHOPCONN"."TRG_STOCK_DISMINUIR" 
AFTER INSERT ON compras_detalle
FOR EACH ROW
BEGIN
  UPDATE productos
     SET stock = stock - :NEW.cantidad
   WHERE codigo = :NEW.codigo_prod;
END;
/
ALTER TRIGGER "ETECHSHOPCONN"."TRG_STOCK_DISMINUIR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USUARIOS_VALIDAR_CORREO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ETECHSHOPCONN"."TRG_USUARIOS_VALIDAR_CORREO" 
BEFORE INSERT OR UPDATE OF correo ON usuarios
FOR EACH ROW
BEGIN
  IF NOT REGEXP_LIKE(:NEW.correo,
     '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
    RAISE_APPLICATION_ERROR(-20010, 'Correo inválido');
  END IF;
END;

/
ALTER TRIGGER "ETECHSHOPCONN"."TRG_USUARIOS_VALIDAR_CORREO" ENABLE;
--------------------------------------------------------
--  DDL for Procedure SP_BUSCAR_PRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_BUSCAR_PRODUCTOS" (
  p_campo IN VARCHAR2,
  p_valor IN VARCHAR2,
  p_out   OUT SYS_REFCURSOR
) IS
  v_sql VARCHAR2(4000);
BEGIN
  v_sql := 'SELECT * FROM PRODUCTOS WHERE ' || p_campo || ' LIKE :1';

  OPEN p_out FOR v_sql USING '%'||p_valor||'%';

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20020, 'Error búsqueda dinámica: '||SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_CAMBIAR_CONTRASENA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_CAMBIAR_CONTRASENA" (
  p_id        IN NUMBER,
  p_hash_nuevo IN VARCHAR2
) AS
BEGIN
  UPDATE usuarios
  SET contrasena = p_hash_nuevo,
      intentos   = 0,
      bloqueado  = 'N'
  WHERE id = p_id;

  COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_CARRITO_AGREGAR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_CARRITO_AGREGAR" (
  p_id_usuario IN NUMBER,
  p_codigo     IN NUMBER,
  p_cantidad   IN NUMBER
) AS
  v_stock NUMBER;
BEGIN
  IF p_cantidad IS NULL OR p_cantidad <= 0 THEN
    RAISE_APPLICATION_ERROR(-20011,'Cantidad invÃ¡lida');
  END IF;

  SELECT stock INTO v_stock
  FROM productos
  WHERE codigo = p_codigo;

  IF v_stock < p_cantidad THEN
    RAISE_APPLICATION_ERROR(-20020,'Stock insuficiente');
  END IF;

  UPDATE carrito
     SET cantidad = cantidad + p_cantidad
   WHERE id_usuario = p_id_usuario
     AND codigo_prod = p_codigo;

  IF SQL%ROWCOUNT = 0 THEN
    INSERT INTO carrito(id_usuario, codigo_prod, cantidad)
    VALUES (p_id_usuario, p_codigo, p_cantidad);
  END IF;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_CARRITO_AGREGAR_DB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_CARRITO_AGREGAR_DB" (
  p_id_usuario IN NUMBER,
  p_codigo     IN NUMBER,
  p_cantidad   IN NUMBER
)
AS
  v_stock NUMBER;
BEGIN
  -- Validar cantidad
  IF p_cantidad IS NULL OR p_cantidad <= 0 THEN
    RAISE_APPLICATION_ERROR(-20011, 'Cantidad invÃ¡lida');
  END IF;

  -- Verificar que el producto exista y obtener stock
  SELECT stock
  INTO v_stock
  FROM productos
  WHERE codigo = p_codigo;

  -- Verificar stock insuficiente
  IF v_stock < p_cantidad THEN
    RAISE_APPLICATION_ERROR(-20020, 'Stock insuficiente');
  END IF;

  -- Intentar actualizar la cantidad si ya existÃ­a en el carrito
  UPDATE carrito
     SET cantidad = cantidad + p_cantidad
   WHERE id_usuario = p_id_usuario
     AND codigo_prod = p_codigo;

  -- Si no actualizÃ³ ninguna fila, insertar nuevo registro
  IF SQL%ROWCOUNT = 0 THEN
    INSERT INTO carrito(id_usuario, codigo_prod, cantidad)
    VALUES (p_id_usuario, p_codigo, p_cantidad);
  END IF;

END;

/
--------------------------------------------------------
--  DDL for Procedure SP_GENERAR_COMPRA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_GENERAR_COMPRA" (
  p_id_usuario IN NUMBER,
  p_id_compra  OUT NUMBER
) AS
  CURSOR cur_items IS
    SELECT c.codigo_prod, c.cantidad, p.precio
      FROM carrito c
      JOIN productos p ON p.codigo=c.codigo_prod
     WHERE c.id_usuario = p_id_usuario;

  v_total NUMBER := 0;
BEGIN
  INSERT INTO compras(id_usuario,total)
  VALUES (p_id_usuario, 0)
  RETURNING id INTO p_id_compra;

  FOR r IN cur_items LOOP
    INSERT INTO compras_detalle(id_compra,codigo_prod,cantidad,precio_unit)
    VALUES (p_id_compra, r.codigo_prod, r.cantidad, r.precio);

    v_total := v_total + (r.cantidad * r.precio);
  END LOOP;

  UPDATE compras SET total=v_total WHERE id=p_id_compra;

  DELETE FROM carrito WHERE id_usuario=p_id_usuario;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20030,'Error generando compra: '||SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERT_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_INSERT_PRODUCTO" (
    p_nombre   IN VARCHAR2,
    p_detalle  IN VARCHAR2,
    p_precio   IN NUMBER,
    p_imagen   IN VARCHAR2
)
AS
BEGIN
    INSERT INTO productos (nombre, detalle, precio, imagen)
    VALUES (p_nombre, p_detalle, p_precio, p_imagen);
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_LOGIN_EXITO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_LOGIN_EXITO" (
  p_id IN NUMBER
) AS
BEGIN
  UPDATE usuarios
  SET intentos = 0,
      bloqueado = 'N'
  WHERE id = p_id;

  COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_LOGIN_FALLO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_LOGIN_FALLO" (
  p_id IN NUMBER
) AS
  v_intentos NUMBER;
BEGIN
  SELECT intentos INTO v_intentos
  FROM usuarios
  WHERE id = p_id
  FOR UPDATE;

  v_intentos := NVL(v_intentos,0) + 1;

  IF v_intentos >= 3 THEN
      UPDATE usuarios
      SET intentos = v_intentos,
          bloqueado = 'S'
      WHERE id = p_id;
  ELSE
      UPDATE usuarios
      SET intentos = v_intentos
      WHERE id = p_id;
  END IF;

  COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_LOGIN_WRAPPER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_LOGIN_WRAPPER" (
  p_correo IN VARCHAR2,
  p_contra IN VARCHAR2,
  p_id_out OUT NUMBER
) AS
BEGIN
  p_id_out := fn_login_usuario(p_correo, p_contra);

  IF p_id_out = 0 THEN
    UPDATE usuarios
       SET intentos = NVL(intentos,0)+1,
           bloqueado = CASE WHEN NVL(intentos,0)+1 >= 3 THEN 'S'
                            ELSE bloqueado END
     WHERE UPPER(correo)=UPPER(p_correo);
  END IF;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_PRODUCTO_UPSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_PRODUCTO_UPSERT" (
  p_codigo    IN OUT NUMBER,
  p_nombre    IN VARCHAR2,
  p_detalle   IN CLOB,
  p_imagen    IN VARCHAR2,
  p_precio    IN NUMBER,
  p_stock     IN NUMBER
) AS
BEGIN
  IF p_codigo IS NULL THEN
    INSERT INTO productos(nombre, detalle, imagen, precio, stock)
    VALUES (p_nombre, p_detalle, p_imagen, p_precio, p_stock)
    RETURNING codigo INTO p_codigo;
  ELSE
    UPDATE productos
       SET nombre=p_nombre, detalle=p_detalle, imagen=p_imagen,
           precio=p_precio, stock=p_stock
     WHERE codigo=p_codigo;
  END IF;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_REGISTRAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ETECHSHOPCONN"."SP_REGISTRAR_USUARIO" (
  p_correo     IN  VARCHAR2,
  p_contra     IN  VARCHAR2,     -- ya viene bcrypt desde PHP
  p_id_out     OUT NUMBER
) AS
BEGIN
  -- Validar correo con REGEXP
  IF NOT REGEXP_LIKE(p_correo,
        '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
    RAISE_APPLICATION_ERROR(-20001, 'Correo inválido');
  END IF;

  -- Insertar usuario
  INSERT INTO usuarios(correo, contrasena, intentos, bloqueado)
  VALUES (UPPER(TRIM(p_correo)), p_contra, 0, 'N')
  RETURNING id INTO p_id_out;

EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    RAISE_APPLICATION_ERROR(-20002, 'El correo ya existe');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20003, 'Error registrando usuario: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Package PKG_ETECHSHOP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ETECHSHOPCONN"."PKG_ETECHSHOP" AS
  -- Inserta auditoría manual
  PROCEDURE P_AUDITAR(
    p_tabla      IN VARCHAR2,
    p_operacion  IN VARCHAR2,
    p_id_reg     IN VARCHAR2,
    p_detalle    IN VARCHAR2
  );

  -- Retorna total comprado por usuario (usa cursor explícito)
  FUNCTION F_TOTAL_USUARIO(p_id_usuario IN NUMBER) RETURN NUMBER;

END PKG_ETECHSHOP;

/
--------------------------------------------------------
--  DDL for Package PKG_REPORTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ETECHSHOPCONN"."PKG_REPORTES" AS
  TYPE t_rc IS REF CURSOR;
  PROCEDURE get_compras_usuario(p_id_usuario IN NUMBER, p_rc OUT t_rc);
END pkg_reportes;

/
--------------------------------------------------------
--  DDL for Package Body PKG_ETECHSHOP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ETECHSHOPCONN"."PKG_ETECHSHOP" AS

  PROCEDURE P_AUDITAR(
    p_tabla      IN VARCHAR2,
    p_operacion  IN VARCHAR2,
    p_id_reg     IN VARCHAR2,
    p_detalle    IN VARCHAR2
  ) IS
  BEGIN
    INSERT INTO AUDITORIA (ID_AUD, TABLA, OPERACION, ID_REGISTRO, USUARIO_BD, DETALLE)
    VALUES (
      SEQ_AUDITORIA.NEXTVAL,
      p_tabla,
      p_operacion,
      p_id_reg,
      SYS_CONTEXT('USERENV','SESSION_USER'),
      p_detalle
    );
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001, 'Error auditando: ' || SQLERRM);
  END P_AUDITAR;


  FUNCTION F_TOTAL_USUARIO(p_id_usuario IN NUMBER) RETURN NUMBER IS
    v_total NUMBER := 0;
    CURSOR c_compras IS
      SELECT total
      FROM compras
      WHERE id_usuario = p_id_usuario;
  BEGIN
    FOR r IN c_compras LOOP
      v_total := v_total + r.total;
    END LOOP;
    RETURN v_total;

  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN 0;
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20002, 'Error calculando total: ' || SQLERRM);
  END F_TOTAL_USUARIO;

END PKG_ETECHSHOP;

/
--------------------------------------------------------
--  DDL for Package Body PKG_REPORTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ETECHSHOPCONN"."PKG_REPORTES" AS
  PROCEDURE get_compras_usuario(p_id_usuario IN NUMBER, p_rc OUT t_rc) IS
  BEGIN
    OPEN p_rc FOR
      SELECT c.id, c.total, c.fecha
        FROM compras c
       WHERE c.id_usuario = p_id_usuario
       ORDER BY c.fecha DESC;
  END;
END pkg_reportes;

/
--------------------------------------------------------
--  DDL for Function FN_LOGIN_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "ETECHSHOPCONN"."FN_LOGIN_USUARIO" (
  p_correo IN VARCHAR2,
  p_hash_out OUT VARCHAR2
) RETURN NUMBER
AS
  v_id       NUMBER;
  v_hash     VARCHAR2(255);
  v_intentos NUMBER;
  v_blk      CHAR(1);
BEGIN
  SELECT id, contrasena, intentos, bloqueado
  INTO   v_id, v_hash, v_intentos, v_blk
  FROM   usuarios
  WHERE  LOWER(correo) = LOWER(TRIM(p_correo));

  p_hash_out := v_hash;

  IF v_blk = 'S' THEN
     RETURN -1; -- bloqueado
  END IF;

  RETURN v_id; -- usuario ok

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    p_hash_out := NULL;
    RETURN 0; -- usuario no existe
END;

/
--------------------------------------------------------
--  Constraints for Table AUDITORIA
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."AUDITORIA" MODIFY ("ID_AUD" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."AUDITORIA" ADD PRIMARY KEY ("ID_AUD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPRAS_DETALLE
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" MODIFY ("ID_DETALLE" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" MODIFY ("ID_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" MODIFY ("CODIGO_PROD" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" MODIFY ("PRECIO_UNIT" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" ADD PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."PRODUCTOS" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."PRODUCTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."PRODUCTOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."PRODUCTOS" ADD PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARRITO
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."CARRITO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."CARRITO" MODIFY ("CODIGO_PROD" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."CARRITO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."CARRITO" ADD CONSTRAINT "PK_CARRITO" PRIMARY KEY ("ID_USUARIO", "CODIGO_PROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."USUARIOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."USUARIOS" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."USUARIOS" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."USUARIOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ETECHSHOPCONN"."USUARIOS" ADD UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPRAS
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."COMPRAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."COMPRAS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ETECHSHOPCONN"."COMPRAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CARRITO
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."CARRITO" ADD FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ETECHSHOPCONN"."USUARIOS" ("ID") ENABLE;
  ALTER TABLE "ETECHSHOPCONN"."CARRITO" ADD FOREIGN KEY ("CODIGO_PROD")
	  REFERENCES "ETECHSHOPCONN"."PRODUCTOS" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPRAS
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."COMPRAS" ADD FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ETECHSHOPCONN"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPRAS_DETALLE
--------------------------------------------------------

  ALTER TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" ADD FOREIGN KEY ("ID_COMPRA")
	  REFERENCES "ETECHSHOPCONN"."COMPRAS" ("ID") ENABLE;
  ALTER TABLE "ETECHSHOPCONN"."COMPRAS_DETALLE" ADD FOREIGN KEY ("CODIGO_PROD")
	  REFERENCES "ETECHSHOPCONN"."PRODUCTOS" ("CODIGO") ENABLE;
