-- =========================================================
-- ETechShop - Script Oracle XE 21c
-- Orden correcto: TABLAS -> SP/FN -> TRIGGERS -> DATOS
-- =========================================================

-- Para que no moleste el $
SET DEFINE OFF;

-- =========================
-- (0) LIMPIEZA OPCIONAL
-- =========================
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_aud_productos_u'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER trg_stock_disminuir'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE pkg_reportes'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_generar_compra'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_carrito_agregar'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_producto_upsert'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_login_wrapper'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION fn_login_usuario'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE sp_registrar_usuario'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE compras_detalle CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE compras CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE carrito CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE productos CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE usuarios CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE auditoria CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =========================
-- (1) TABLAS
-- =========================

CREATE TABLE usuarios (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correo       VARCHAR2(255) NOT NULL UNIQUE,
  contrasena   VARCHAR2(255) NOT NULL,
  intentos     NUMBER DEFAULT 0,
  bloqueado    CHAR(1) DEFAULT 'N',
  fch_crea     DATE DEFAULT SYSDATE
);

CREATE TABLE productos (
  codigo       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(255) NOT NULL,
  detalle      VARCHAR2(1024),
  imagen       VARCHAR2(455),
  precio       NUMBER(10,2) NOT NULL,
  stock        NUMBER DEFAULT 0,
  fch_crea     DATE DEFAULT SYSDATE
);

CREATE TABLE compras (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario   NUMBER NOT NULL REFERENCES usuarios(id),
  total        NUMBER(10,2),
  fecha        DATE DEFAULT SYSDATE
);

CREATE TABLE compras_detalle (
  id_detalle   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_compra    NUMBER NOT NULL REFERENCES compras(id),
  codigo_prod  NUMBER NOT NULL REFERENCES productos(codigo),
  cantidad     NUMBER NOT NULL,
  precio_unit  NUMBER(10,2) NOT NULL
);

CREATE TABLE carrito (
  id_usuario   NUMBER NOT NULL REFERENCES usuarios(id),
  codigo_prod  NUMBER NOT NULL REFERENCES productos(codigo),
  cantidad     NUMBER NOT NULL,
  CONSTRAINT pk_carrito PRIMARY KEY (id_usuario, codigo_prod)
);

CREATE TABLE auditoria (
  id_aud       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla        VARCHAR2(50),
  operacion    VARCHAR2(10),
  id_registro  VARCHAR2(50),
  usuario_bd   VARCHAR2(50),
  fch_evento   DATE DEFAULT SYSDATE,
  detalle      VARCHAR2(4000)
);

-- =========================
-- (2) PROCEDURES / FUNCTIONS
-- =========================

CREATE OR REPLACE PROCEDURE sp_registrar_usuario(
  p_correo     IN  VARCHAR2,
  p_contra     IN  VARCHAR2,
  p_id_out     OUT NUMBER
) AS
BEGIN
  IF NOT REGEXP_LIKE(p_correo, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
    RAISE_APPLICATION_ERROR(-20001,'Correo inválido');
  END IF;

  INSERT INTO usuarios(correo, contrasena)
  VALUES (UPPER(p_correo), p_contra)
  RETURNING id INTO p_id_out;

EXCEPTION 
  WHEN DUP_VAL_ON_INDEX THEN
    RAISE_APPLICATION_ERROR(-20002,'El correo ya existe');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20003,'Error registrando usuario: '||SQLERRM);
END;
/

CREATE OR REPLACE FUNCTION fn_login_usuario(
  p_correo   IN VARCHAR2,
  p_contra   IN VARCHAR2
) RETURN NUMBER
AS
  v_id   NUMBER;
  v_blk  CHAR(1);
BEGIN
  SELECT id, bloqueado INTO v_id, v_blk
  FROM usuarios
  WHERE UPPER(correo)=UPPER(p_correo) AND contrasena=p_contra;

  IF v_blk = 'S' THEN
    RAISE_APPLICATION_ERROR(-20010,'Cuenta bloqueada');
  END IF;

  UPDATE usuarios SET intentos=0 WHERE id=v_id;
  RETURN v_id;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/

CREATE OR REPLACE PROCEDURE sp_login_wrapper(
  p_correo IN VARCHAR2,
  p_contra IN VARCHAR2,
  p_id_out OUT NUMBER
) AS
BEGIN
  p_id_out := fn_login_usuario(p_correo, p_contra);

  IF p_id_out = 0 THEN
    UPDATE usuarios
       SET intentos = NVL(intentos,0)+1,
           bloqueado = CASE WHEN NVL(intentos,0)+1 >= 3 THEN 'S' 
                            ELSE bloqueado END
     WHERE UPPER(correo)=UPPER(p_correo);
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE sp_producto_upsert(
  p_codigo    IN OUT NUMBER,
  p_nombre    IN VARCHAR2,
  p_detalle   IN CLOB,
  p_imagen    IN VARCHAR2,
  p_precio    IN NUMBER,
  p_stock     IN NUMBER
) AS
BEGIN
  IF p_codigo IS NULL THEN
    INSERT INTO productos(nombre, detalle, imagen, precio, stock)
    VALUES (p_nombre, p_detalle, p_imagen, p_precio, p_stock)
    RETURNING codigo INTO p_codigo;
  ELSE
    UPDATE productos
       SET nombre=p_nombre, detalle=p_detalle, imagen=p_imagen,
           precio=p_precio, stock=p_stock
     WHERE codigo=p_codigo;
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE sp_carrito_agregar(
  p_id_usuario IN NUMBER,
  p_codigo     IN NUMBER,
  p_cantidad   IN NUMBER
) AS
  v_stock NUMBER;
BEGIN
  IF p_cantidad IS NULL OR p_cantidad <= 0 THEN
    RAISE_APPLICATION_ERROR(-20011,'Cantidad inválida');
  END IF;

  SELECT stock INTO v_stock
  FROM productos
  WHERE codigo = p_codigo;

  IF v_stock < p_cantidad THEN
    RAISE_APPLICATION_ERROR(-20020,'Stock insuficiente');
  END IF;

  UPDATE carrito
     SET cantidad = cantidad + p_cantidad
   WHERE id_usuario = p_id_usuario
     AND codigo_prod = p_codigo;

  IF SQL%ROWCOUNT = 0 THEN
    INSERT INTO carrito(id_usuario, codigo_prod, cantidad)
    VALUES (p_id_usuario, p_codigo, p_cantidad);
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE sp_generar_compra(
  p_id_usuario IN NUMBER,
  p_id_compra  OUT NUMBER
) AS
  CURSOR cur_items IS
    SELECT c.codigo_prod, c.cantidad, p.precio
      FROM carrito c 
      JOIN productos p ON p.codigo=c.codigo_prod
     WHERE c.id_usuario = p_id_usuario;

  v_total NUMBER := 0;
BEGIN
  INSERT INTO compras(id_usuario,total) 
  VALUES (p_id_usuario, 0)
  RETURNING id INTO p_id_compra;

  FOR r IN cur_items LOOP
    INSERT INTO compras_detalle(id_compra,codigo_prod,cantidad,precio_unit)
    VALUES (p_id_compra, r.codigo_prod, r.cantidad, r.precio);

    v_total := v_total + (r.cantidad * r.precio);
  END LOOP;

  UPDATE compras SET total=v_total WHERE id=p_id_compra;

  DELETE FROM carrito WHERE id_usuario=p_id_usuario; 

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20030,'Error generando compra: '||SQLERRM);
END;
/

-- =========================
-- (3) TRIGGERS
-- =========================

CREATE OR REPLACE TRIGGER trg_aud_productos_u
AFTER UPDATE OF precio, stock ON productos
FOR EACH ROW
DECLARE
  v_detalle VARCHAR2(400);
BEGIN
  IF NVL(:OLD.precio, -1) <> NVL(:NEW.precio, -1) THEN
    v_detalle := NVL(v_detalle,'') || 'precio: '||:OLD.precio||' -> '||:NEW.precio||' ';
  END IF;

  IF NVL(:OLD.stock, -1) <> NVL(:NEW.stock, -1) THEN
    v_detalle := NVL(v_detalle,'') || 'stock: '||:OLD.stock||' -> '||:NEW.stock||' ';
  END IF;

  IF v_detalle IS NOT NULL THEN
    INSERT INTO auditoria(tabla, operacion, id_registro, usuario_bd, detalle)
    VALUES ('PRODUCTOS',
            'UPDATE',
            TO_CHAR(:NEW.codigo),
            SYS_CONTEXT('USERENV','SESSION_USER'),
            TRIM(v_detalle));
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_stock_disminuir
AFTER INSERT ON compras_detalle
FOR EACH ROW
BEGIN
  UPDATE productos
     SET stock = stock - :NEW.cantidad
   WHERE codigo = :NEW.codigo_prod;
END;
/

-- =========================
-- (4) REPORTES (PACKAGE)
-- =========================

CREATE OR REPLACE PACKAGE pkg_reportes AS
  TYPE t_rc IS REF CURSOR;
  PROCEDURE get_compras_usuario(p_id_usuario IN NUMBER, p_rc OUT t_rc);
END pkg_reportes;
/

CREATE OR REPLACE PACKAGE BODY pkg_reportes AS
  PROCEDURE get_compras_usuario(p_id_usuario IN NUMBER, p_rc OUT t_rc) IS
  BEGIN
    OPEN p_rc FOR
      SELECT c.id, c.total, c.fecha
        FROM compras c
       WHERE c.id_usuario = p_id_usuario
       ORDER BY c.fecha DESC;
  END;
END pkg_reportes;
/

-- =========================
-- (5) DATOS INICIALES
-- =========================

INSERT INTO productos (codigo, nombre, detalle, imagen, precio, stock) VALUES 
(1,'Audifonos', 'Accesorios', 'https://www.steren.cr/media/catalog/product/cache/b69086f136192bea7a4d681a8eaf533d/image/20986abca/audifonos-bluetooth-con-bateria-de-hasta-30-h.jpg', 9600, 10);

INSERT INTO productos (codigo, nombre, detalle, imagen, precio, stock) VALUES 
(2,'Cámara', 'Especial para fotógrafos', 'https://innovacellcr.com/cdn/shop/files/camara-instantanea-instax-mini-11-innovacell-1-24280790040665.png?v=1699022342', 250000, 5);

INSERT INTO productos (codigo, nombre, detalle, imagen, precio, stock) VALUES 
(3,'Iphone 14 Pro', 'Dispositivo Móvil', 'https://www.mugen.crkaizen.com/wp-content/uploads/2023/04/Apple-iPhone-14-Pro-iPhone-14-Pro-Max-silver-220907-geo_inline.jpg.large_.jpg', 750000, 8);

INSERT INTO productos (codigo, nombre, detalle, imagen, precio, stock) VALUES 
(4,'Samsung S23 Ultra', 'Dispositivo móvil', 'https://images.samsung.com/latin/smartphones/galaxy-s23-ultra/images/galaxy-s23-ultra-highlights-colors-lavender-back-s.jpg', 500000, 7);

INSERT INTO productos (codigo, nombre, detalle, imagen, precio, stock) VALUES 
(5,'Mac', 'Laptop', 'https://www.istore.cr/cdn/shop/products/macbook-pro-m2-13-istore-pulgadas-silver-costa-rica.jpg?v=1676696928&width=940', 1750000, 3);

INSERT INTO productos (codigo, nombre, detalle, imagen, precio, stock) VALUES 
(6,'Samsung TV Crystal UHD', 'TV', 'https://m.media-amazon.com/images/I/81YA7--7UyL.jpg', 1000000, 4);

COMMIT;

PROMPT ✅ Script Oracle ETechShop ejecutado correctamente.
