--Ejecutar en Oracle 19C Sql Developer:

CREATE USER etechShopConn IDENTIFIED BY Pass123$
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE TO etechShopConn;
ALTER USER app_user QUOTA UNLIMITED ON users;

--Abrir Xampp> Apache > Config > php.ini > descomentar "extension=oci8_19" quitando el ; y reiniciar. Tras el reinicio, abrir y buscar la sección "oci8" en esta ubicación http://localhost/etechshop/phpInfo.php
CREATE TABLE usuarios (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correo       VARCHAR2(255) NOT NULL UNIQUE,
  contrasena   VARCHAR2(255) NOT NULL,
  intentos     NUMBER DEFAULT 0,
  bloqueado    CHAR(1) DEFAULT 'N',
  fch_crea     DATE DEFAULT SYSDATE
);

CREATE TABLE productos (
  codigo       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(255) NOT NULL,
  detalle      VARCHAR2(1024),
  imagen       VARCHAR2(455),
  precio       NUMBER(10,2) NOT NULL,
  stock        NUMBER DEFAULT 0,
  fch_crea     DATE DEFAULT SYSDATE
);

CREATE TABLE compras (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario   NUMBER NOT NULL REFERENCES usuarios(id),
  total        NUMBER(10,2),
  fecha        DATE DEFAULT SYSDATE
);

CREATE TABLE compras_detalle (
  id_detalle   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_compra    NUMBER NOT NULL REFERENCES compras(id),
  codigo_prod  NUMBER NOT NULL REFERENCES productos(codigo),
  cantidad     NUMBER NOT NULL,
  precio_unit  NUMBER(10,2) NOT NULL
);

CREATE TABLE carrito (
  id_usuario   NUMBER NOT NULL REFERENCES usuarios(id),
  codigo_prod  NUMBER NOT NULL REFERENCES productos(codigo),
  cantidad     NUMBER NOT NULL,
  CONSTRAINT pk_carrito PRIMARY KEY (id_usuario, codigo_prod)
);

CREATE TABLE auditoria (
  id_aud       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla        VARCHAR2(50),
  operacion    VARCHAR2(10),
  id_registro  VARCHAR2(50),
  usuario_bd   VARCHAR2(50),
  fch_evento   DATE DEFAULT SYSDATE,
  detalle      VARCHAR2(4000)
);
---Procedimiento para registrar usuario, va a permitir que el usuario utilice un correo que obligatoriamente
---debe llevar un @ terminar con al menos dos letras (.com, .co, .es)
CREATE OR REPLACE PROCEDURE sp_registrar_usuario(
  p_correo     IN  VARCHAR2,
  p_contra     IN  VARCHAR2,
  p_id_out     OUT NUMBER
) AS
BEGIN
  IF NOT REGEXP_LIKE(p_correo, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
    RAISE_APPLICATION_ERROR(-20001,'Correo inválido');
  END IF;

  INSERT INTO usuarios(correo, contrasena)
  VALUES (UPPER(p_correo), p_contra)
  RETURNING id INTO p_id_out;
EXCEPTION 
---excepciones si el correo ya esta guardardo en la base de datos o sucede algun error 
  WHEN DUP_VAL_ON_INDEX THEN
    RAISE_APPLICATION_ERROR(-20002,'El correo ya existe');
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20003,'Error registrando usuario: '||SQLERRM);
END;
/

--Procedimiento que permite que el usuario haga login, se hace un wrapper que va a llevar 
--la cuenta de intentos y bloquear la cuenta despues de tres intentos 
CREATE OR REPLACE FUNCTION fn_login_usuario(
  p_correo   IN VARCHAR2,
  p_contra   IN VARCHAR2
) RETURN NUMBER
AS
  v_id   NUMBER;
  v_blk  CHAR(1);
BEGIN
  SELECT id, bloqueado INTO v_id, v_blk
  FROM usuarios
  ---valida la contraseña y el correo
  WHERE UPPER(correo)=UPPER(p_correo) AND contrasena=p_contra;
---bloqueo de la cuenta si el wrapper llega a tres intentos 
  IF v_blk = 'S' THEN
    RAISE_APPLICATION_ERROR(-20010,'Cuenta bloqueada');
  END IF;
  UPDATE usuarios SET intentos=0 WHERE id=v_id;
  RETURN v_id;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/
--creacion del wrapper 
CREATE OR REPLACE PROCEDURE sp_login_wrapper(
  p_correo IN VARCHAR2,
  p_contra IN VARCHAR2,
  p_id_out OUT NUMBER
) AS
BEGIN
--validación del correo y contraseña
  p_id_out := fn_login_usuario(p_correo, p_contra);
  IF p_id_out = 0 THEN
    UPDATE usuarios
       SET intentos = NVL(intentos,0)+1,
           bloqueado = CASE WHEN NVL(intentos,0)+1 >= 3 THEN 'S' 
           ELSE bloqueado 
           END
     WHERE UPPER(correo)=UPPER(p_correo);
  END IF;
END;
/

--editar o agregar un producto
--se utiliza un merge para hacer un upsert (update-insert)
CREATE OR REPLACE PROCEDURE sp_producto_upsert(
  p_codigo    IN OUT NUMBER,
  p_nombre    IN VARCHAR2,
  p_detalle   IN CLOB,
  p_imagen    IN VARCHAR2,
  p_precio    IN NUMBER,
  p_stock     IN NUMBER
) AS
BEGIN
  IF p_codigo IS NULL THEN
    INSERT INTO productos(nombre, detalle, imagen, precio, stock)
    VALUES (p_nombre, p_detalle, p_imagen, p_precio, p_stock)
    RETURNING codigo INTO p_codigo;
  ELSE
    UPDATE productos
       SET nombre=p_nombre, detalle=p_detalle, imagen=p_imagen,
           precio=p_precio, stock=p_stock
     WHERE codigo=p_codigo;
  END IF;
END;
/
--trigger para auditar cuando a un producto se la cambia el precio o el stock
CREATE OR REPLACE TRIGGER trg_aud_productos_u
AFTER UPDATE OF precio, stock ON productos
FOR EACH ROW
DECLARE
  v_detalle VARCHAR2(400);
BEGIN
  -- información del cambio 
  IF NVL(:OLD.precio, -1) <> NVL(:NEW.precio, -1) THEN
    v_detalle := NVL(v_detalle,'') || 'precio: '||:OLD.precio||' -> '||:NEW.precio||' ';
  END IF;

  IF NVL(:OLD.stock, -1) <> NVL(:NEW.stock, -1) THEN
    v_detalle := NVL(v_detalle,'') || 'stock: '||:OLD.stock||' -> '||:NEW.stock||' ';
  END IF;

  -- solo inserta en AUDITORIA si hay cambios reales
  IF v_detalle IS NOT NULL THEN
    INSERT INTO auditoria(tabla, operacion, id_registro, usuario_bd, detalle)
    VALUES ('PRODUCTOS',
            'UPDATE',
            TO_CHAR(:NEW.codigo),
            SYS_CONTEXT('USERENV','SESSION_USER'),
            TRIM(v_detalle));
  END IF;
END;
/

--verificación del stock
CREATE OR REPLACE PROCEDURE sp_carrito_agregar(
  p_id_usuario IN NUMBER,
  p_codigo     IN NUMBER,
  p_cantidad   IN NUMBER
) AS
  v_stock NUMBER;
BEGIN
  IF p_cantidad IS NULL OR p_cantidad <= 0 THEN
    RAISE_APPLICATION_ERROR(-20011,'Cantidad inválida');
  END IF;
--validar stock disponible
  SELECT stock INTO v_stock
  FROM productos
  WHERE codigo = p_codigo;
--error si el stock no es suficiente 
  IF v_stock < p_cantidad THEN
    RAISE_APPLICATION_ERROR(-20020,'Stock insuficiente');
  END IF;
--si el producto ya estaba en el carrito se le incrementa la cantidad 
  UPDATE carrito
     SET cantidad = cantidad + p_cantidad
   WHERE id_usuario = p_id_usuario
     AND codigo_prod = p_codigo;
--inserta el producto si no estaba en el carrito 
  IF SQL%ROWCOUNT = 0 THEN
    INSERT INTO carrito(id_usuario, codigo_prod, cantidad)
    VALUES (p_id_usuario, p_codigo, p_cantidad);
  END IF;
END;
/
--- Ejemplo EXEC sp_carrito_agregar_db(1, 100, 3);


--Generar compra
CREATE OR REPLACE PROCEDURE sp_generar_compra(
  p_id_usuario IN NUMBER,
  p_id_compra  OUT NUMBER
) AS
  CURSOR cur_items IS
    SELECT c.codigo_prod, c.cantidad, p.precio
      FROM carrito c JOIN productos p ON p.codigo=c.codigo_prod
     WHERE c.id_usuario = p_id_usuario;
  v_total NUMBER := 0;
BEGIN
  INSERT INTO compras(id_usuario,total) VALUES (p_id_usuario, 0)
  RETURNING id INTO p_id_compra;
  FOR r IN cur_items LOOP
    INSERT INTO compras_detalle(id_compra,codigo_prod,cantidad,precio_unit)
    VALUES (p_id_compra, r.codigo_prod, r.cantidad, r.precio);
    v_total := v_total + (r.cantidad * r.precio);
  END LOOP;

  UPDATE compras SET total=v_total WHERE id=p_id_compra;
-- limpiar carrito
  DELETE FROM carrito WHERE id_usuario=p_id_usuario; 
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20030,'Error generando compra: '||SQLERRM);
END;
/
--Trigger para disminuir el stock una vez se hace la compra 
CREATE OR REPLACE TRIGGER trg_stock_disminuir
AFTER INSERT ON compras_detalle
FOR EACH ROW
BEGIN
  UPDATE productos
     SET stock = stock - :NEW.cantidad
   WHERE codigo = :NEW.codigo_prod;
END;
/

--Historial de compras de usuario
CREATE OR REPLACE PACKAGE pkg_reportes AS
  TYPE t_rc IS REF CURSOR;
  PROCEDURE get_compras_usuario(p_id_usuario IN NUMBER, p_rc OUT t_rc);
END pkg_reportes;
/

CREATE OR REPLACE PACKAGE BODY pkg_reportes AS
  PROCEDURE get_compras_usuario(p_id_usuario IN NUMBER, p_rc OUT t_rc) IS
  BEGIN
    OPEN p_rc FOR
      SELECT c.id, c.total, c.fecha
        FROM compras c
       WHERE c.id_usuario = p_id_usuario
       ORDER BY c.fecha DESC;
  END;
END pkg_reportes;
/
